### ISSUE TITLE
Enum for "storeOpType" in Router.sol

### ISSUE THREAD

**Issue by tcheee** [usePicnic/jam#1]
Hey,

I wonder why not use an Enum (https://solidity-by-example.org/enum/) to increase readibility of the "storeOpType"? Is is to optimise gas consumption in any way?

**Comment by pgbrandao** [comment]
Excellent point. There were no gas optimisations in mind. An enum would enhance readability with no drawbacks that I can see. Suggestion heeded!

**Comment by pgbrandao** [comment]
Implemented on b878605
